/**
 * Fotos de cardápio mantidas no próprio app.
 *
 * O mapa é intencionalmente explícito: só substitui itens que ainda usam
 * placeholders ilustrados no banco. Produtos que já têm fotografia real
 * continuam usando `image_url` normalmente.
 */
const MENU_IMAGE_OVERRIDES: Readonly<Record<string, string>> = {
  "4-queijos-premium": "/menu/point-da-pizza/4-queijos-premium.webp",
  "banana-canela-cartola": "/menu/point-da-pizza/banana-canela-cartola.webp",
  "brigadeiro-doce": "/menu/point-da-pizza/brigadeiro-doce.webp",
  "calzone-calabresa-acebolada": "/menu/point-da-pizza/calzone-calabresa-acebolada.webp",
  "calzone-calabresa-cheddar": "/menu/point-da-pizza/calzone-calabresa-cheddar.webp",
  "calzone-calabresa-sem-cebola": "/menu/point-da-pizza/calzone-calabresa-sem-cebola.webp",
  "calzone-frango-catupiry": "/menu/point-da-pizza/calzone-frango-catupiry.webp",
  "calzone-frango-mucarela": "/menu/point-da-pizza/calzone-frango-mucarela.webp",
  "calzone-mucarela": "/menu/point-da-pizza/calzone-mucarela.webp",
  "calzone-portuguesa": "/menu/point-da-pizza/calzone-portuguesa.webp",
  "chocolate-banana-granulado": "/menu/point-da-pizza/chocolate-banana-granulado.webp",
  "creme-ninho-pacoca": "/menu/point-da-pizza/creme-ninho-pacoca.webp",
  "ninho-chocolate-doce": "/menu/point-da-pizza/ninho-chocolate-doce.webp",
  "ninho-chocolate-media": "/menu/point-da-pizza/ninho-chocolate-media.webp",
  "prestigio-doce": "/menu/point-da-pizza/prestigio-doce.webp",
  "romeu-e-julieta": "/menu/point-da-pizza/romeu-e-julieta.webp",
  "frango-catupiry-individual": "/menu/point-da-pizza/frango-catupiry-individual.webp",
  "frango-mucarela-media": "/menu/point-da-pizza/frango-mucarela-media.webp",
  "meio-calabresa-meio-frango-media": "/menu/point-da-pizza/meio-calabresa-meio-frango-media.webp",
  "mucarela-tomate-media": "/menu/point-da-pizza/mucarela-tomate-media.webp",
  "portuguesa-media": "/menu/point-da-pizza/portuguesa-media.webp",
  "grande-tradicional-1-sabor": "/menu/point-da-pizza/pizza-mucarela-base.webp",
  "grande-tradicional-2-sabores": "/menu/point-da-pizza/meio-calabresa-meio-frango-media.webp",
  "combo-meio-frango-meio-calabresa-coca": "/menu/point-da-pizza/combo-meio-frango-meio-calabresa-coca.webp",
  "combo-frango-catupiry-coca": "/menu/point-da-pizza/combo-frango-catupiry-coca.webp",
  "combo-mucarela-8-coca": "/menu/point-da-pizza/combo-mucarela-8-coca.webp",
  "combo-portuguesa-8-coca-1l": "/menu/point-da-pizza/combo-portuguesa-8-coca-1l.webp",
  "combo-familia-master": "/menu/point-da-pizza/combo-familia-master.webp",
  "combo-gold": "/menu/point-da-pizza/combo-gold.webp",
  "combo-supreme": "/menu/point-da-pizza/combo-supreme.webp",
  "combo-portuguesa-8-coca-lata": "/menu/point-da-pizza/combo-portuguesa-8-coca-lata.webp",
  "combo-bauru-8-coca-1l": "/menu/point-da-pizza/combo-bauru-8-coca-1l.webp",
  "combo-bauru-8-coca-lata": "/menu/point-da-pizza/combo-bauru-8-coca-lata.webp",
  "combo-pepperoni-8-coca": "/menu/point-da-pizza/combo-pepperoni-8-coca.webp",
  "combo-individual-calabresa-coca-lata": "/menu/point-da-pizza/combo-individual-calabresa-coca-lata.webp",
  "combo-individual-mucarela-coca-lata": "/menu/point-da-pizza/combo-individual-mucarela-coca-lata.webp",
  "combo-individual-frango-mucarela-coca-lata": "/menu/point-da-pizza/combo-individual-frango-mucarela-coca-lata.webp",
  "pdp-coca-lata-350": "/menu/shared/cola.webp",
  "pdp-coca-zero-lata-350": "/menu/shared/cola.webp",
  "pdp-guarana-lata-350": "/menu/shared/guarana.webp",
  "pdp-guarana-zero-lata-350": "/menu/shared/guarana.webp",
  "pdp-sprite-lata-350": "/menu/shared/limao.webp",
  "pdp-fanta-lata-350": "/menu/shared/laranja.webp",
  "pdp-coca-zero-garrafa-1l": "/menu/shared/cola.webp",
  "pdp-guarana-garrafa-1l": "/menu/shared/guarana.webp",
  "pdp-fanta-garrafa-1l": "/menu/shared/laranja.webp",
  "pdp-h2oh-garrafa-1l": "/menu/shared/limao.webp",
  "pdp-coca-garrafa-2l": "/menu/shared/cola.webp",
  "pdp-coca-zero-garrafa-2l": "/menu/shared/cola.webp",
  "pdp-guarana-garrafa-2l": "/menu/shared/guarana.webp",
  "pdp-kuat-garrafa-2l": "/menu/shared/guarana.webp",
  "pdp-agua-com-gas-500": "/menu/shared/agua-com-gas.webp",
  "lasanha-5-queijos": "/menu/lucianis/lasanha-5-queijos.webp",
  "parmegiana-frango": "/menu/lucianis/parmegiana-frango.webp",
  "parmegiana-file-mignon": "/menu/lucianis/parmegiana-file-mignon.webp",
  "risoto-tilapia": "/menu/lucianis/risoto-tilapia.webp",
  "coca-zero-lata-350": "/menu/shared/cola.webp",
  "sprite-lata-350": "/menu/shared/limao.webp",
  "guarana-lata-350": "/menu/shared/guarana.webp",
  "fanta-lata-350": "/menu/shared/laranja.webp",
  "coca-zero-garrafa-1l": "/menu/shared/cola.webp",
  "fanta-garrafa-1l": "/menu/shared/laranja.webp",
  "h2oh-garrafa-1l": "/menu/shared/limao.webp",
  "agua-com-gas-500": "/menu/shared/agua-com-gas.webp",
  "h2oh-500": "/menu/shared/limao.webp",
};

export function resolveMenuImage(slug: string, imageUrl: string | null): string | null {
  return MENU_IMAGE_OVERRIDES[slug] ?? imageUrl;
}
